name: Continuous Integration Checks - Kotlin

on: [push, pull_request]

jobs:
  check-kotlin:
    runs-on: ubuntu-latest

    env:
      LDK_NODE_JVM_DIR: bindings/kotlin/ldk-node-jvm
      LDK_NODE_ANDROID_DIR: bindings/kotlin/ldk-node-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Install LLVM, Clang and Libssl-dev
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm clang libssl-dev pkg-config librust-openssl-sys-dev

#      - name: Set PKG_CONFIG_PATH
#        run: echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/" >> $GITHUB_ENV

#      - name: find files
#        run: |
#          apt-file update
#          apt-file list libssl-dev

      - name: Set OPENSSL_DIR
        run: echo "OPENSSL_DIR=/usr" >> $GITHUB_ENV
##
      - name: Set OPENSSL_INCLUDE_DIR
        run: |
          echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV 

#
#      - name: Check OpenSSL headers directory
#        run: ls -l /usr/include/openssl
#
      - name: Set OPENSSL_LIB_DIR
        run: echo "OPENSSL_LIB_DIR=/usr/lib64" >> $GITHUB_ENV

      - name: Install Android NDK for Android 21
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
          unzip -q android-ndk-r21-linux-x86_64.zip
          echo "ANDROID_NDK_ROOT=$(pwd)/android-ndk-r21" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_ENV



#      - name: Run ktlintCheck on ldk-node-jvm
#        run: |
#          cd $LDK_NODE_JVM_DIR
#          ./gradlew ktlintCheck
#
#      - name: Run ktlintCheck on ldk-node-android
#        run: |
#          cd $LDK_NODE_ANDROID_DIR
#          ./gradlew ktlintCheck

#      - name: Generate Kotlin JVM
#        run: ./scripts/uniffi_bindgen_generate_kotlin.sh

      - name: Generate Kotlin Android
        run: ./scripts/uniffi_bindgen_generate_kotlin_android.sh

      - name: Start bitcoind and electrs
        run: docker compose up -d

      - name: Run ldk-node-jvm tests
        run: |
          cd $LDK_NODE_JVM_DIR
          ./gradlew test -Penv=ci

      - name: Run ldk-node-android tests
        run: |
          cd $LDK_NODE_ANDROID_DIR
          ./gradlew test
